nick: ModderationPB-UNCONFIGURED
alt-nicks:
- '%NICK%_'
- '%NICK%__'
login: ModderationPB-UNCONFIGURED
realname: ''
server: irc.synirc.net
port: 7001
tls: false
ssl: true
trust-all-certs: true
bind: ''
max-line-length: 440
charset: ''
show-motd: false
autoconnect: true
password: ''
ident-password: ''
command-prefix: .
quit-message: '&r[&5PurpleIRC&r] &rGood bye!'
message-delay: 1000
finger-reply: ''
raw-message-on-connect: false
raw-message: auth name pass
relay-private-chat: false
command-notify:
  enabled: false
  mode: msg
  recipients:
  - '#nst'
  ignore:
  - /example
part-invalid-channels: false
part-invalid-channels-message: I should not be here! Bye!
channel-auto-join-delay: 20
custom-prefixes:
- AwesomeNick [AwesomePrefix]
- '*!*sarah@example.com [Owner]'
custom-prefix-default: '[IRC]'
replace-first-occurrences:
- 'AwesomeNick : &r:'
- '*!*sarah@example.com : &r:'
channels:
  '#minecraft-test':
    worlds:
    - '*'
    autojoin: true
    modes: ''
    password: ''
    topic: New topic
    topic-protect: false
    topic-chanserv: false
    shortify: true
    enable-filtering: false
    filter-list:
    - ModderationPB
    enabled-messages:
    - console-chat
    - game-action
    - game-chat
    - game-death
    - game-kick
    - game-join
    - game-quit
    - irc-action
    - irc-chat
    - irc-pchat
    - irc-join
    - irc-kick
    - irc-part
    - irc-topic
    - irc-quit
    - irc-nickchange
    - irc-mode
    - irc-notice
    - dynmap-web-chat
    - irc-dynmap-web-chat
    - irc-action-dynmap-web-chat
    ops:
    - '*!*sarah@example.com'
    muted:
    - KuShy
    ignore-irc-chat: false
    invalid-command:
      private: false
      ctcp: false
    raw-message: ''
    raw-message-on-join: false
    join-notice:
      enabled: false
      cooldown: 60
      private: true
      ctcp: true
      message: /list
    commands:
      chat:
        modes: '*'
        private: false
        ctcp: false
        game_command: '@chat'
        private_listen: true
        channel_listen: true
      ochat:
        modes: '*'
        private: false
        ctcp: false
        game_command: '@ochat'
        private_listen: true
        channel_listen: true
      msg:
        modes: '*'
        private: true
        ctcp: false
        game_command: '@msg'
        private_listen: true
        channel_listen: true
      list:
        modes: '*'
        private: false
        ctcp: false
        game_command: '@list'
        private_listen: true
        channel_listen: true
      help:
        modes: '*'
        private: false
        ctcp: false
        game_command: '@help'
        private_listen: true
        channel_listen: true
      uptime:
        modes: '*'
        private: false
        ctcp: false
        game_command: '@uptime'
        private_listen: true
        channel_listen: true
      version:
        modes: '*'
        private: false
        ctcp: false
        game_command: '@versionfull'
        private_listen: true
        channel_listen: true
      lag:
        modes: '*'
        private: false
        ctcp: false
        game_command: lag
        private_listen: true
        channel_listen: true
      lv:
        modes: o
        private: 'false'
        ctcp: 'false'
        game_command: '@list'
        extra_commands:
        - '@version'
        private_listen: 'true'
        channel_listen: 'true'
        perm: ''
